version: '3.1'

services:
  database:
    
    image: mysql
    container_name: evaLS-database

    environment: 
      MYSQL_DATABASE: "evaLS"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    
    ports:
      - "3310:3306"

    volumes:
      - './mysql:/var/lib/mysql'
